Adding Cod'INSA student association to other association list
Campus-INSA-CVL/campus-website pull request #100
Opened 2022-11-24 20:08 UTC by firemat

### Summary

This PR adds the Cod'INSA student association to other association list, and fixes a minor typo in the presentation text for other association view.

Since I didn't find any specific infos on what should be done to validate the addition of a complete association beforehand, I hope this will not be an issue to add it by using this PR.

### Other Information

If this PR is validated, the app will have 3 inter-INSA associations registered. You may want to add in the future other inter-insa student associations like the FIIG too.

2022-11-25 11:46 UTC, Barbapapazes commented on content/federation/les-autres-assos/index.md
> +> Les assos qui ne sont pas fédérées, mais qui existent tout de même !
```suggestion
> Les assos qui ne sont pas fédérées mais qui existent tout de même !
```

2022-11-25 11:48 UTC, Barbapapazes requested changes
Merci pour l'ajout et avec plaisir pour ajouter la FIIG

2022-11-25 11:48 UTC, Barbapapazes commented on content/federation/les-autres-assos/index.md
> +> Les assos qui ne sont pas fédérées, mais qui existent tout de même !
Il n'y a pas besoin d'une virgule.

2022-11-25 11:48 UTC, Barbapapazes commented on content/federation/les-autres-assos/associations/cod-insa/index.md
> +  &#099;&#111;&#110;&#116;&#097;&#099;&#116;<span style="display:none">cod</span>&#064;<span style="display:none">insa</span>&#099;&#111;&#100;&#105;&#110;&#115;&#097;&#046;&#111;&#114;&#103;<span st
ça correspond à quoi tous ces caractères spéciaux ?

2022-11-25 18:04 UTC, firemat commented on content/federation/les-autres-assos/associations/cod-insa/index.md
> +  &#099;&#111;&#110;&#116;&#097;&#099;&#116;<span style="display:none">cod</span>&#064;<span style="display:none">insa</span>&#099;&#111;&#100;&#105;&#110;&#115;&#097;&#046;&#111;&#114;&#103;<span st
Cela correspond à l'adresse mail de contact de l'asso [formaté en ASCII](http://www.wbwip.com/wbw/emailencoder.html).

Avec la combinaison de texte caché (balises `span` ici), cela permet de rendre légèrement plus difficile le scraping de l'adresse mail.

2022-11-26 12:01 UTC, Barbapapazes commented on content/federation/les-autres-assos/associations/cod-insa/index.md
> +  &#099;&#111;&#110;&#116;&#097;&#099;&#116;<span style="display:none">cod</span>&#064;<span style="display:none">insa</span>&#099;&#111;&#100;&#105;&#110;&#115;&#097;&#046;&#111;&#114;&#103;<span st
ça roule !

2022-11-26 12:01 UTC, Barbapapazes approved these changes

2022-11-26 12:02 UTC, merged